name: CI

on: push

jobs:
  coverage:
    container: ghcr.io/abu-lib/smoke-test-env:1.0.0
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DABU_COVERAGE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Debug --output-on-failure

      - name: Create code coverage report
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Debug --target abu_coverage_report

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{github.workspace}}/build/abu_coverage_report

  build-and-test-ubuntu:
    needs: coverage
    strategy:
      matrix:
        compiler: [g++-11]
        build_type: [Debug, Release]

    container: ghcr.io/abu-lib/smoke-test-env:1.0.0
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
  
  build-and-test-macos:
    needs: coverage
    strategy:
      matrix:
        compiler: [g++-11]
        build_type: [Debug, Release]

    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure
        env:
          CXX: ${{matrix.compiler}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure

  build-and-test-windows:
    needs: coverage
    strategy:
      matrix:
        toolset: [ClangCL, host=x64, host=x86]
        arch: [Win32, x64]
        build_type: [Debug, Release]

    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -T ${{matrix.toolset}} -A ${{matrix.arch}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure
